import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({

  en_US: {
    home: 'Home',
    getEmp: 'Fetch Data',
    Welcometo: 'Welcome to',
    eShop: 'eShop',
    Digitizationofcatalogs: 'Digitization of catalogs',
    createstore: 'create store',
    emailaddress: 'email address',
    storename: 'store name',
    BysigningupIagreetoeShopTermsofServiceandprivacypolicy: 'By signing up, I agree to eShop Terms of Service and privacy policy',
    continue: 'continue',
    'Alreadyhaveanaccount': 'Already have an account? Login',
    WebMall: 'Web Mall',
    Desc: 'Add product images to your store with our next generation image creation workflow',
    After: 'After ',
    Before: 'Before',
    ProductCategory: 'Product Category',
    Bowl: 'Bowl ',
    Bag: 'Bag',
    other: 'other',
    Car: 'Car',
    Home: 'Home ',
    store: 'store',
    Startshooting: 'Start shooting',
    Logout: 'Logout',
    //ShreeMarket, Sector32, Gurgaon: 'Shree Market, Sector 32, Gurgaon',
    Completed: 'Completed',
    InProcess: 'In Process',
    Youhavenotcreatedanyprojectyet: 'You have not created any project yet',
    CreateProject: 'Create Project',
    ProjectName: 'Project Name',
    CreateProject: 'Create Project ',
    Wouldyouliketosaveandcontinuelater: 'Would you like to save and continue later',
    AbandonShoot: 'Abandon Shoot',
    MarkShootDone: 'Mark Shoot Done',
    Saveandcontinuelater: 'Save and continue later',
    Luggage: 'Luggage',
    clutch: 'clutch',
    Duffle: 'Duffle',
    Rucksack: 'Rucksack',
    Satchel: 'Satchel',
    TrolleyBag: 'Trolley Bag',
    SatchelFront: 'Satchel Front',
    SatchelBack: 'Satchel Back',
    SatchelonModel: 'Satchel on Model',
    Satchelinterior: 'Satchel interior',
    Done: 'Done',
    Reviewimages: 'Review images',
    Details: 'Details',
    Projectcategory: 'Project category',
    Capturedimages: 'Captured images',
    confirm: 'confirm',
    Oncewereadywithimagesyoucanaddtheminstore: 'Images will be saved at store in "In Process" state. Once we ready with images you can add them in store',
    Completed: 'Completed',
    Inprocess: 'In process',
    ProjectName: 'Project Name',
    thDecember2021: '9th December 2021',
    "ID/ SKUNo.": 'ID/SKU No.',
    SKUNo: 'SKU No.',
    ProductName: 'Product Name',
    Quantity: 'Quantity ',
    Description: 'Description',
    Priceperitem: 'Price per item ',
    Writehere: 'Write here',
    Confirm: 'Confirm',
    Assoonasyouclickconfirm: 'As soon as you click confirm, ', 
    thisprojectwilladdtoyourstore: 'this project will add to your store',
    AddtostoreLuggage: 'Add to store: Luggage',
    LUGG0098: 'LUGG0098',
    Luggagebag: 'Luggage bag',
    Pleaseaddprice: 'Please add price',
    PhoneNumber: 'Phone Number',
    Verifyaphonenumber: 'Verify a phone number',
    Storesetting: 'Store setting',
    Paymentcriteria: 'Payment criteria',
    Add: 'Add',
    Cash: 'Cash',
    UPI: 'UPI',
    CreditDebitCards: 'Card',
    Fulfillmentcriteria: 'Fulfillment criteria',
    Storepickup: 'Store pickup',
    HomeDelivery: 'Home Delivery',
    Save: 'Save',
    login:'Login Store'

  },
  hi_IN: {
    home: 'होम',
    getEmp: 'डेटा प्राप्त करें',
    Welcometo: 'स्वागत',
    eShop: 'ईशॉप',
    Digitizationofcatalogs: 'कैटलॉग का डिजिटाइजेशन',
    createstore: 'स्टोर बनाएं',
    emailaddress: 'मेल पता',
    storename: 'स्टोर नाम',
    BysigningupIagreetoeShopTermsofServiceandprivacypolicy: 'साइन अप करके, मैं ईशॉप सेवा की शर्तों और गोपनीयता नीति से सहमत हूं',
    continue: 'जारी रखें',
    'Alreadyhaveanaccount': 'क्या आपके पास पहले से एक खाता मौजूद है? लॉग इन करें',
    WebMall: 'वेब मॉल',
    Desc: 'हमारे अगली पीढ़ी के छवि निर्माण कार्यप्रवाह के साथ अपने स्टोर में उत्पाद छवियां जोड़ें',
    After: 'बाद',
    Before: 'पहले',
    ProductCategory: 'उत्पाद श्रेणी',
    Bowl: 'कटोरा',
    Bag: 'थैला',
    other: 'अन्य',
    Car: 'कार',
    Home: 'घर',
    store: 'दुकान',
    Startshooting: 'शूटिंग शुरू करें',
    Logout: 'लॉग आउट',
    //ShreeMarket, Sector32, Gurgaon: 'श्री मार्केट, सेक्टर 32, गुडगाँव',
    Completed: 'पूरा हुआ',
    InProcess: 'प्रक्रिया में',
    Youhavenotcreatedanyprojectyet: 'आपने अभी तक कोई प्रोजेक्ट नहीं बनाया है',
    CreateProject: 'प्रोजेक्ट बनाएं',
    ProjectName: 'परियोजना का नाम',
    CreateProject: 'प्रोजेक्ट बनाएं',
    Wouldyouliketosaveandcontinuelater: 'क्या आप बाद में सहेजना और जारी रखना चाहेंगे',
    AbandonShoot: 'छोड़ो',
    MarkShootDone: 'शूट किया हुआ',
    Saveandcontinuelater: 'सहेजें और बाद में जारी रखें',
    Luggage: 'सामान',
    clutch: 'क्लच',
    Duffle: 'डफले',
    Rucksack: 'रूकसाक',
    Satchel: 'सैचल',
    TrolleyBag: 'ट्रॉली बैग',
    SatchelFront: 'सैचल सामने का',
    SatchelBack: 'सैचल पीछे का',
    SatchelonModel: 'मॉडल पर सैचल',
    Satchelinterior: 'सैचल इंटीरियर',
    Done: 'किया हुआ',
    Reviewimages: 'छवियों की समीक्षा करें',
    Details: 'विवरण',
    Projectcategory: 'परियोजना श्रेणी',
    Capturedimages: 'कैप्चर की गई छवियां',
    confirm: 'पुष्टि करना',
    Oncewereadywithimagesyoucanaddtheminstore: 'छवियों को स्टोर पर "इन प्रोसेस" स्थिति में सहेजा जाएगा। एक बार जब हम छवियों के साथ तैयार हो जाते हैं तो आप उन्हें स्टोर में जोड़ सकते हैं',
    Completed: 'पूरा हुआ',
    Inprocess: 'प्रक्रिया में',
    ProjectName: 'परियोजना का नाम',
    'thDecember2021': '9 दिसंबर 2021',
    'ID / SKUNo.': 'आईडी/एसकेयू नं.',
    SKUNo: 'एसकेयू नं.',
    ProductName: 'प्रोडक्ट का नाम',
    Quantity: 'मात्रा',
    Description: 'विवरण',
    Priceperitem: 'मूल्य प्रति आइटम',
    Writehere: 'यहाँ लिखें',
    Confirm: 'पुष्टि करना',
    Assoonasyouclickconfirm : 'जैसे ही आप कन्फर्म पर क्लिक करेंगे', 
    thisprojectwilladdtoyourstore: 'यह प्रोजेक्ट आपके स्टोर में जुड़ जाएगा',
    AddtostoreLuggage: 'स्टोर में जोड़ें: सामान',
    LUGG0098: 'LUGG0098',
    Luggagebag: 'सामान का थैला',
    Pleaseaddprice: 'कृपया कीमत जोड़ें',
    PhoneNumber: 'फ़ोन नंबर',
    Verifyaphonenumber: 'फ़ोन नंबर सत्यापित करें',
    Storesetting: 'स्टोर सेटिंग',
    Paymentcriteria: 'भुगतान मानदंड',
    Add: 'जोड़ें',
    Cash: 'नकद',
    UPI: 'यूपीआई',
    CreditDebitCards: 'क्रेडिट/डेबिट कार्ड',
    Fulfillmentcriteria: 'पूर्ति मानदंड',
    Storepickup: 'दुकान से लॆना',
    HomeDelivery: 'घर पहुँचाना',
    Save: 'सहेजें',
    login:'लॉगिन स्टोर'


  },



});

export default strings; 