export const GET_PAGE_LIST_REQUEST = 'GET_PAGE_LIST_REQUEST';
export const GET_PAGE_LIST_SUCCESS = 'GET_PAGE_LIST_SUCCESS';
export const GET_PAGE_LIST_FAILURE = 'GET_PAGE_LIST_FAILURE';
export const CREATE_STORE_REQUEST = 'CREATE_STORE_REQUEST';
export const CREATE_STORE_SUCCESS = 'CREATE_STORE_SUCCESS';
export const CREATE_STORE_FAILURE = 'CREATE_STORE_FAILURE';

export const LOGIN_STORE_REQUEST = 'LOGIN_STORE_REQUEST';
export const LOGIN_STORE_SUCCESS = 'LOGIN_STORE_SUCCESS';
export const LOGIN_STORE_FAILURE = 'LOGIN_STORE_FAILURE';